//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Client.IntermediaryDecaux {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stations", Namespace="http://schemas.datacontract.org/2004/07/IntermediaryWS")]
    [System.SerializableAttribute()]
    public partial class Stations : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BikesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LngField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bikes {
            get {
                return this.BikesField;
            }
            set {
                if ((this.BikesField.Equals(value) != true)) {
                    this.BikesField = value;
                    this.RaisePropertyChanged("Bikes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Lat {
            get {
                return this.LatField;
            }
            set {
                if ((this.LatField.Equals(value) != true)) {
                    this.LatField = value;
                    this.RaisePropertyChanged("Lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Lng {
            get {
                return this.LngField;
            }
            set {
                if ((this.LngField.Equals(value) != true)) {
                    this.LngField = value;
                    this.RaisePropertyChanged("Lng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stat", Namespace="http://schemas.datacontract.org/2004/07/IntermediaryWS")]
    [System.SerializableAttribute()]
    public partial class Stat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan AverageDelayIWS1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientRequestGoogle1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientRequestIWS1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CounterAverageDelayIWSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WSVelibRequest1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan AverageDelayIWS1 {
            get {
                return this.AverageDelayIWS1Field;
            }
            set {
                if ((this.AverageDelayIWS1Field.Equals(value) != true)) {
                    this.AverageDelayIWS1Field = value;
                    this.RaisePropertyChanged("AverageDelayIWS1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientRequestGoogle1 {
            get {
                return this.ClientRequestGoogle1Field;
            }
            set {
                if ((this.ClientRequestGoogle1Field.Equals(value) != true)) {
                    this.ClientRequestGoogle1Field = value;
                    this.RaisePropertyChanged("ClientRequestGoogle1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientRequestIWS1 {
            get {
                return this.ClientRequestIWS1Field;
            }
            set {
                if ((this.ClientRequestIWS1Field.Equals(value) != true)) {
                    this.ClientRequestIWS1Field = value;
                    this.RaisePropertyChanged("ClientRequestIWS1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CounterAverageDelayIWS {
            get {
                return this.CounterAverageDelayIWSField;
            }
            set {
                if ((this.CounterAverageDelayIWSField.Equals(value) != true)) {
                    this.CounterAverageDelayIWSField = value;
                    this.RaisePropertyChanged("CounterAverageDelayIWS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WSVelibRequest1 {
            get {
                return this.WSVelibRequest1Field;
            }
            set {
                if ((this.WSVelibRequest1Field.Equals(value) != true)) {
                    this.WSVelibRequest1Field = value;
                    this.RaisePropertyChanged("WSVelibRequest1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IntermediaryDecaux.IIntermediaryDecaux")]
    public interface IIntermediaryDecaux {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryDecaux/GetStationsInfoCity", ReplyAction="http://tempuri.org/IIntermediaryDecaux/GetStationsInfoCityResponse")]
        string GetStationsInfoCity(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryDecaux/GetStationsInfoCity", ReplyAction="http://tempuri.org/IIntermediaryDecaux/GetStationsInfoCityResponse")]
        System.Threading.Tasks.Task<string> GetStationsInfoCityAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryDecaux/FindStation", ReplyAction="http://tempuri.org/IIntermediaryDecaux/FindStationResponse")]
        double[] FindStation(string depart, string arrive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryDecaux/FindStation", ReplyAction="http://tempuri.org/IIntermediaryDecaux/FindStationResponse")]
        System.Threading.Tasks.Task<double[]> FindStationAsync(string depart, string arrive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryDecaux/GetAllCities", ReplyAction="http://tempuri.org/IIntermediaryDecaux/GetAllCitiesResponse")]
        string[] GetAllCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryDecaux/GetAllCities", ReplyAction="http://tempuri.org/IIntermediaryDecaux/GetAllCitiesResponse")]
        System.Threading.Tasks.Task<string[]> GetAllCitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryDecaux/GetStationCity", ReplyAction="http://tempuri.org/IIntermediaryDecaux/GetStationCityResponse")]
        Web_Client.IntermediaryDecaux.Stations[] GetStationCity(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryDecaux/GetStationCity", ReplyAction="http://tempuri.org/IIntermediaryDecaux/GetStationCityResponse")]
        System.Threading.Tasks.Task<Web_Client.IntermediaryDecaux.Stations[]> GetStationCityAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryDecaux/GetStat", ReplyAction="http://tempuri.org/IIntermediaryDecaux/GetStatResponse")]
        Web_Client.IntermediaryDecaux.Stat GetStat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryDecaux/GetStat", ReplyAction="http://tempuri.org/IIntermediaryDecaux/GetStatResponse")]
        System.Threading.Tasks.Task<Web_Client.IntermediaryDecaux.Stat> GetStatAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryDecaux/SetTimer", ReplyAction="http://tempuri.org/IIntermediaryDecaux/SetTimerResponse")]
        void SetTimer(System.TimeSpan timer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryDecaux/SetTimer", ReplyAction="http://tempuri.org/IIntermediaryDecaux/SetTimerResponse")]
        System.Threading.Tasks.Task SetTimerAsync(System.TimeSpan timer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntermediaryDecauxChannel : Web_Client.IntermediaryDecaux.IIntermediaryDecaux, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntermediaryDecauxClient : System.ServiceModel.ClientBase<Web_Client.IntermediaryDecaux.IIntermediaryDecaux>, Web_Client.IntermediaryDecaux.IIntermediaryDecaux {
        
        public IntermediaryDecauxClient() {
        }
        
        public IntermediaryDecauxClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntermediaryDecauxClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntermediaryDecauxClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntermediaryDecauxClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetStationsInfoCity(int value) {
            return base.Channel.GetStationsInfoCity(value);
        }
        
        public System.Threading.Tasks.Task<string> GetStationsInfoCityAsync(int value) {
            return base.Channel.GetStationsInfoCityAsync(value);
        }
        
        public double[] FindStation(string depart, string arrive) {
            return base.Channel.FindStation(depart, arrive);
        }
        
        public System.Threading.Tasks.Task<double[]> FindStationAsync(string depart, string arrive) {
            return base.Channel.FindStationAsync(depart, arrive);
        }
        
        public string[] GetAllCities() {
            return base.Channel.GetAllCities();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllCitiesAsync() {
            return base.Channel.GetAllCitiesAsync();
        }
        
        public Web_Client.IntermediaryDecaux.Stations[] GetStationCity(string city) {
            return base.Channel.GetStationCity(city);
        }
        
        public System.Threading.Tasks.Task<Web_Client.IntermediaryDecaux.Stations[]> GetStationCityAsync(string city) {
            return base.Channel.GetStationCityAsync(city);
        }
        
        public Web_Client.IntermediaryDecaux.Stat GetStat() {
            return base.Channel.GetStat();
        }
        
        public System.Threading.Tasks.Task<Web_Client.IntermediaryDecaux.Stat> GetStatAsync() {
            return base.Channel.GetStatAsync();
        }
        
        public void SetTimer(System.TimeSpan timer) {
            base.Channel.SetTimer(timer);
        }
        
        public System.Threading.Tasks.Task SetTimerAsync(System.TimeSpan timer) {
            return base.Channel.SetTimerAsync(timer);
        }
    }
}
