//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Client.IntermediaryDecauxClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stat", Namespace="http://schemas.datacontract.org/2004/07/IntermediaryWS")]
    [System.SerializableAttribute()]
    public partial class Stat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan AverageDelayIWS1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientRequestGoogle1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientRequestIWS1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CounterAverageDelayIWSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WSVelibRequest1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan AverageDelayIWS1 {
            get {
                return this.AverageDelayIWS1Field;
            }
            set {
                if ((this.AverageDelayIWS1Field.Equals(value) != true)) {
                    this.AverageDelayIWS1Field = value;
                    this.RaisePropertyChanged("AverageDelayIWS1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientRequestGoogle1 {
            get {
                return this.ClientRequestGoogle1Field;
            }
            set {
                if ((this.ClientRequestGoogle1Field.Equals(value) != true)) {
                    this.ClientRequestGoogle1Field = value;
                    this.RaisePropertyChanged("ClientRequestGoogle1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientRequestIWS1 {
            get {
                return this.ClientRequestIWS1Field;
            }
            set {
                if ((this.ClientRequestIWS1Field.Equals(value) != true)) {
                    this.ClientRequestIWS1Field = value;
                    this.RaisePropertyChanged("ClientRequestIWS1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CounterAverageDelayIWS {
            get {
                return this.CounterAverageDelayIWSField;
            }
            set {
                if ((this.CounterAverageDelayIWSField.Equals(value) != true)) {
                    this.CounterAverageDelayIWSField = value;
                    this.RaisePropertyChanged("CounterAverageDelayIWS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WSVelibRequest1 {
            get {
                return this.WSVelibRequest1Field;
            }
            set {
                if ((this.WSVelibRequest1Field.Equals(value) != true)) {
                    this.WSVelibRequest1Field = value;
                    this.RaisePropertyChanged("WSVelibRequest1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IntermediaryDecauxClient.IAdmin")]
    public interface IAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/GetStat", ReplyAction="http://tempuri.org/IAdmin/GetStatResponse")]
        WS_Client.IntermediaryDecauxClient.Stat GetStat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/GetStat", ReplyAction="http://tempuri.org/IAdmin/GetStatResponse")]
        System.Threading.Tasks.Task<WS_Client.IntermediaryDecauxClient.Stat> GetStatAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/SetTimer", ReplyAction="http://tempuri.org/IAdmin/SetTimerResponse")]
        void SetTimer(System.TimeSpan timer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/SetTimer", ReplyAction="http://tempuri.org/IAdmin/SetTimerResponse")]
        System.Threading.Tasks.Task SetTimerAsync(System.TimeSpan timer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminChannel : WS_Client.IntermediaryDecauxClient.IAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminClient : System.ServiceModel.ClientBase<WS_Client.IntermediaryDecauxClient.IAdmin>, WS_Client.IntermediaryDecauxClient.IAdmin {
        
        public AdminClient() {
        }
        
        public AdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WS_Client.IntermediaryDecauxClient.Stat GetStat() {
            return base.Channel.GetStat();
        }
        
        public System.Threading.Tasks.Task<WS_Client.IntermediaryDecauxClient.Stat> GetStatAsync() {
            return base.Channel.GetStatAsync();
        }
        
        public void SetTimer(System.TimeSpan timer) {
            base.Channel.SetTimer(timer);
        }
        
        public System.Threading.Tasks.Task SetTimerAsync(System.TimeSpan timer) {
            return base.Channel.SetTimerAsync(timer);
        }
    }
}
